//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKyTucXa
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Thang { get; set; }
        public Nullable<long> Tien { get; set; }
        public string MaSinhVien { get; set; }
        public string MaPhong { get; set; }
    
        public virtual PHONG PHONG { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
